<?php

// DO NOT ALTER THESE VALUES AS THEY ARE
// ESSENTIAL TO THE FUNCTIONALITY OF THIS API WRAPPER

define('MAILAPI_ENDPOINT', 'https://api.mailermailer.com/1.0/');

define('MAILAPI_VERSION', '1.0.5');

define ('MAILAPI_PARTNER', 'MM');

?>
